### ISSUE TITLE
'names' attribute [8] must be the same length as the vector [4] error

### ISSUE THREAD

**Issue by rjbehnke** [ropensci/rnoaa#281] opened 2018-10-17 22:23 UTC
I'm parsing the entire ISD data set using isd_parse, and the following errors are occurring for parallel and single core parses for the code following.  I attached two files that this occurs for, but I can send more if you need me to.  

Error in checkForRemoteErrors(val) : 
  one node produced an error: 'names' attribute [8] must be the same length as the vector [4]

Error in names(object) <- nm : 
  'names' attribute [8] must be the same length as the vector [4]

parsed = isd_parse('I:\\ISD\\1975\\725110-14751-1975.gz',addition=TRUE,parallel = TRUE,cores=2)

**Comment by sckott** [comment] 2018-10-18 17:20
@rjbehnke what's your session info?

**Comment by rubenjbehnke** [comment] 2018-10-18 23:45
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] isdparser_0.2.0

loaded via a namespace (and not attached):
[1] compiler_3.5.1 parallel_3.5.1 tools_3.5.1    yaml_2.2.0    
Warning messages:
1: In findVar(sym, cntxt) :
  closing unused connection 4 (<-DESKTOP-R3OO8R5:11581)
2: In findVar(sym, cntxt) :
  closing unused connection 3 (<-DESKTOP-R3OO8R5:11581)

**Comment by sckott** [comment] 2018-10-19 22:49
@rjbehnke sounds this concerns `isdparser` package, correct?

**Comment by sckott** [comment] 2018-10-19 23:11
@rjbehnke pretty sure this is fixed, possibly was fixed in https://github.com/ropensci/isdparser/issues/15 a while back. i tried with two of those files and couldn't reproduce the problem, both worked fine. 

can you try the dev version of `isdparser` and see if that works. I'll try to get that pushed to cran soon

**Comment by rubenjbehnke** [comment] 2018-10-19 23:34
After installing the dev version, it works.  Thank you.

Ruben

**Closed** 2018-10-19 23:35 UTC

**Comment by rjbehnke** [comment] 2018-10-19 23:49
Just to make sure, the files that did parse are parsed correctly, right?  Or do I need to redo all of them?

**Comment by sckott** [comment] 2018-10-19 23:58
what do you mean by parsed correctly? There were no errors or anything, but I didn't validate them per se

**Comment by rubenjbehnke** [comment] 2018-10-20 02:15
I was referring to the files that parsed for me using the pre-development version of isdparser.  I'm sure they did because there were no errors or anything, but I thought I'd ask in case there are any changes to the isd_parser function.
